process.env.PUBMED_AUTO_SEARCH='false';
const test=require('node:test');
const assert=require('node:assert/strict');
const {server}=require('../server');

let base;
test.before(async()=>{await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));base=`http://127.0.0.1:${server.address().port}`});
test.after(()=>server.close());

test('health, readiness and diagnostics endpoints expose safe operational state',async()=>{let response=await fetch(`${base}/api/health`);assert.equal(response.status,200);const body=await response.json();assert.equal(body.mode,'agent-orchestrated-mvp');assert.equal(body.version,'2.31.0');assert.equal(body.authEnabled,false);assert.equal(body.shuttingDown,false);assert.equal(response.headers.get('x-frame-options'),'DENY');assert.match(response.headers.get('content-security-policy'),/script-src 'self'/);response=await fetch(`${base}/api/health/ready`);assert.equal(response.status,200);const ready=await response.json();assert.equal(ready.status,'ready');assert.equal(ready.database.ok,true);response=await fetch(`${base}/api/health/diagnostics`);assert.equal(response.status,200);const diagnostics=await response.json();assert.equal(diagnostics.status,'healthy');assert.equal(diagnostics.backups.state,'disabled');assert.equal(diagnostics.offsiteBackups.state,'disabled');assert.equal(diagnostics.backups.lastChecksum,undefined);assert.equal(diagnostics.offsiteBackups.lastRequestId,undefined);assert.equal(typeof diagnostics.workload.projects,'number');assert.ok(diagnostics.runtime.uptimeSeconds>=0)});
test('web app includes authentication, monitoring, report exports and resumable Agent transitions',async()=>{const page=await fetch(base).then(response=>response.text()),script=await fetch(`${base}/app.js`).then(response=>response.text());assert.match(page,/id="authGate"/);assert.match(page,/id="loginForm"/);assert.match(page,/id="agentTransition"/);assert.match(page,/id="importStudy"/);assert.match(page,/id="backupStudy"/);assert.match(page,/id="serviceStatus"/);assert.match(page,/aria-live="polite"/);assert.match(page,/id="transitionMinimize"/);assert.match(script,/X-CSRF-Token/);assert.match(script,/forkStudy/);assert.match(script,/updateBackupControls/);assert.match(script,/updateServiceStatus/);assert.match(script,/health\/diagnostics/);assert.match(script,/analysis-report-pdf/);assert.match(script,/analysis-report-docx/);assert.match(script,/analysis-tables-download/);assert.match(script,/analysis-manuscript-download/);assert.match(script,/transitionCancel/);assert.match(script,/resilientFetch/);assert.match(script,/method:'DELETE'/);assert.match(script,/已恢复正在运行的研究任务/);assert.match(script,/服务器重启后已恢复此任务/);assert.match(script,/正在核验官方代码本/);assert.match(script,/正在验证 CDC 数据文件/);assert.match(script,/正在缓存 NHANES 数据/);assert.match(script,/正在执行 R survey 分析/);assert.match(script,/multiple_imputation/);assert.match(script,/modelImputationCount/);assert.match(script,/modelImputationIterations/);assert.match(script,/modelImputationSeed/);assert.match(script,/计数型（quasipoisson）/);assert.match(script,/const execution=kind==='qc'/);assert.match(script,/if\(kind==='qc'\)\{bindFullExecution/);assert.equal((script.match(/id=\"runFullExecution\"/g)||[]).length,1)});
test('web app exposes the PubMed method-evidence matrix and preserves extracted method details',async()=>{const script=await fetch(`${base}/app.js`).then(response=>response.text());assert.match(script,/renderMethodEvidence/);assert.match(script,/PubMed 方法学证据矩阵/);assert.match(script,/methodDetails:a\.methods\?\.details/)});
test('new-study screen provides guided, template and free-form question creation',async()=>{const page=await fetch(base).then(response=>response.text()),script=await fetch(`${base}/app.js`).then(response=>response.text());assert.match(page,/data-start-mode="guided"/);assert.match(page,/data-start-mode="examples"/);assert.match(page,/data-start-mode="free"/);assert.match(page,/id="guideExposure"/);assert.match(page,/id="guideOutcome"/);assert.match(page,/id="guidePopulation"/);assert.match(page,/id="guideCycles"/);assert.match(page,/id="promptScore"/);assert.match(page,/复杂抽样权重始终启用/);assert.match(script,/function buildGuidedQuestion/);assert.match(script,/function applyResearchTemplate/);assert.match(script,/请先填写/);assert.doesNotMatch(script,/if\(!\$\('#question'\)\.value\)\$\('#question'\)\.value=\$\$\('\[data-example\]'\)\[0\]/)});
test('project API preserves the validated structured research brief',async()=>{const researchBrief={source:'guided',exposure:'血清 25(OH)D 水平',outcome:'抑郁症状',population:'美国 60 岁及以上老年人',cycles:'使用 2017–2018 年 NHANES 周期',aim:'分析关联',covariates:['年龄','性别'],analysisOptions:['进行稳健性和敏感性分析'],notes:'排除妊娠者'},response=await fetch(`${base}/api/projects`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({question:'在美国老年人中分析血清维生素D与抑郁症状的关联。',researchBrief})}),project=await response.json();assert.equal(response.status,201);assert.equal(project.researchBrief.schemaVersion,'1.0');assert.equal(project.intent.parser.mode,'structured-brief-v1');assert.equal(project.intent.population.ageMin,60);assert.equal(project.intent.exposure.source,'researcher_brief');assert.deepEqual(project.intent.analysisPreferences,['进行稳健性和敏感性分析'])});

test('sidebar keeps recent projects scrollable above the fixed profile area',async()=>{const styles=await fetch(`${base}/styles.css`).then(response=>response.text());assert.match(styles,/\.layout>aside\{[^}]*height:100vh[^}]*overflow:hidden/);assert.match(styles,/\.layout>aside nav\{[^}]*min-height:0[^}]*overflow-y:auto/);assert.match(styles,/\.profile\{[^}]*position:static[^}]*flex:0 0 auto/)});

test('catalog endpoint returns provenance',async()=>{const response=await fetch(`${base}/api/catalog/variables?q=LBXVIDMS`);const body=await response.json();assert.equal(body.items.length,1);assert.equal(body.items[0].provenance.publisher,'CDC/NCHS')});

test('backup endpoints stay closed while administrator authentication is disabled',async()=>{let response=await fetch(`${base}/api/projects/import`,{method:'POST',headers:{'content-type':'application/json'},body:'{}'});assert.equal(response.status,403);assert.equal((await response.json()).error.code,'AUTH_REQUIRED_FOR_BACKUP');response=await fetch(`${base}/api/projects/prj_1234567890abcdef/backup`);assert.equal(response.status,403);assert.equal((await response.json()).error.code,'AUTH_REQUIRED_FOR_BACKUP')});

test('project lifecycle reaches the approval gate',async()=>{
  let response=await fetch(`${base}/api/projects`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({question:'Study serum vitamin D and depressive symptoms among NHANES adults'})});
  assert.equal(response.status,201);const project=await response.json();
  response=await fetch(`${base}/api/projects/${project.id}/run`,{method:'POST'});assert.equal(response.status,202);
  await new Promise(resolve=>setTimeout(resolve,700));
  response=await fetch(`${base}/api/projects/${project.id}`);const completed=await response.json();
  assert.equal(completed.status,'awaiting_approval');assert.equal(completed.variables.length,11);assert.equal(completed.feasibility.status,'executable');assert.equal(completed.literature.mode,'disabled');assert.match(completed.literature.query,/NHANES/);
  response=await fetch(`${base}/api/projects/${project.id}/evidence`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({query:'vitamin D AND depression AND NHANES',items:[{pmid:'123',title:'A study',decision:'include',methodTags:['survey-weighted analysis','logistic regression'],methodDetails:{studyDesign:'cross-sectional',modelFamilies:['logistic regression'],complexSurvey:'reported'},publicationTypes:['Journal Article'],relevanceScore:100}]})});
  assert.equal(response.status,200);const screened=await response.json();assert.equal(screened.evidence.summary.included,1);assert.equal(screened.protocol.evidenceIncluded,1);assert.equal(screened.protocol.evidenceStatus,'screened_title_abstract');assert.equal(screened.evidence.methodEvidence.matrix[0].pmid,'123');assert.equal(screened.evidence.methodEvidence.decisions.find(item=>item.topic==='主模型').status,'supported_and_applicable');assert.equal(screened.status,'awaiting_approval');
  response=await fetch(`${base}/api/projects/${project.id}/data-manifest`);assert.equal(response.status,200);const dataManifest=await response.json();assert.equal(dataManifest.files.length,24);assert.ok(dataManifest.files.every(file=>file.url.startsWith('https://wwwn.cdc.gov/')));
  response=await fetch(`${base}/api/projects/${project.id}/data-cache`);assert.equal(response.status,200);assert.equal((await response.json()).status,'not_started');
  response=await fetch(`${base}/api/projects/${project.id}/analysis-run`);assert.equal(response.status,200);assert.equal((await response.json()).status,'not_started');
  response=await fetch(`${base}/api/projects/${project.id}/execute`);assert.equal(response.status,200);assert.equal((await response.json()).status,'not_started');
  response=await fetch(`${base}/api/projects/${project.id}/execute`,{method:'DELETE'});assert.equal(response.status,200);assert.equal((await response.json()).status,'not_started');
  response=await fetch(`${base}/api/projects/${project.id}/data-cache`,{method:'DELETE'});assert.equal(response.status,200);assert.equal((await response.json()).status,'not_started');
  response=await fetch(`${base}/api/projects/${project.id}/analysis-run`,{method:'DELETE'});assert.equal(response.status,200);assert.equal((await response.json()).status,'not_started');
  response=await fetch(`${base}/api/projects/${project.id}/execute`,{method:'POST'});assert.equal(response.status,409);assert.equal((await response.json()).error.code,'ANALYSIS_NOT_READY');
  response=await fetch(`${base}/api/projects/${project.id}/analysis-package-download`);assert.equal(response.status,200);assert.equal(response.headers.get('content-type'),'application/gzip');assert.ok((await response.arrayBuffer()).byteLength>1000);
  response=await fetch(`${base}/api/projects/${project.id}/approve`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({actor:'tester',decisions:{outcome_definition:'PHQ-9 >= 10',exposure_parameterization:'per 10 nmol/L',covariate_set:'age, sex, race, PIR, BMI',missing_data:'complete case',association_only:true}})});
  assert.equal(response.status,200);assert.equal((await response.json()).status,'approved');
  response=await fetch(`${base}/api/projects/${project.id}/execute`);assert.equal(response.status,200);assert.equal((await response.json()).status,'not_started');
  response=await fetch(`${base}/api/projects?limit=10`);assert.equal(response.status,200);const listing=await response.json();assert.ok(listing.items.some(item=>item.id===project.id));
  response=await fetch(`${base}/api/projects/${project.id}/audit`);assert.equal(response.status,200);const audit=await response.json();assert.equal(audit.chainVerified,true);assert.ok(audit.events.length>=8);assert.ok(audit.events.every(event=>event.verified===true));
});
