const test=require('node:test'),assert=require('node:assert/strict');
const {createModelSpec,verifyModelSpec}=require('../src/model-spec');
const {generateModelScript}=require('../src/model-script');
function project(){const cycles=['2017-2018'];return {status:'awaiting_approval',intent:{cycles},cleaningApproval:{digest:'clean'},variables:[{role:'exposure',variable:'LBXBPB',sourceFile:'PBCD_J',cycles,confirmationStatus:'codebook_and_cleaning_approved'},{role:'outcome',variable:'BPXSY1',sourceFile:'BPX_J',cycles,confirmationStatus:'codebook_and_cleaning_approved'},{role:'covariate',variable:'RIDAGEYR',cycles,confirmationStatus:'codebook_and_cleaning_approved'},{role:'covariate',variable:'RIAGENDR',cycles,confirmationStatus:'codebook_and_cleaning_approved'},{role:'design',variable:'WTMEC2YR',cycles},{role:'design',variable:'SDMVSTRA',cycles},{role:'design',variable:'SDMVPSU',cycles}]}}
const input={outcomeFamily:'continuous',exposureTransform:'log2',outcomeTransform:'raw',populationAgeMin:20,weightVariable:'WTMEC2YR',covariates:[{variable:'RIDAGEYR',encoding:'continuous'},{variable:'RIAGENDR',encoding:'factor'}],acknowledgeAssociationOnly:true};
test('approved model spec freezes population, cycle mappings and explicit encodings',()=>{const spec=createModelSpec(project(),input);assert.equal(spec.status,'approved_for_code_generation_not_execution');assert.equal(spec.population.ageMin,20);assert.equal(spec.covariates[1].encoding,'factor');assert.equal(spec.digest.length,64)});
test('generated model uses survey design, a valid formula, population gate and audited JSON result',()=>{const script=generateModelScript(createModelSpec(project(),input));assert.match(script,/svydesign/);assert.match(script,/svyglm\(analysis_outcome ~ analysis_exposure/);assert.match(script,/RIDAGEYR.*>= 20/);assert.match(script,/generic_survey_v1/);assert.match(script,/write_json/);assert.match(script,/TRUE ~ NA_real_/);assert.match(script,/log2/);assert.match(script,/factor/);assert.match(script,/Nonfinite model result/);assert.doesNotMatch(script,/\.data\[\[|\.default/)});
test('model approval rejects unconfirmed mappings and causal overclaim',()=>{const p=project();p.variables=p.variables.filter(x=>x.role!=='outcome');assert.throws(()=>createModelSpec(p,input),/结局/);assert.throws(()=>createModelSpec(project(),{...input,acknowledgeAssociationOnly:false}),/关联/)});
test('model digest detects changes after researcher approval',()=>{const spec=createModelSpec(project(),input);assert.equal(verifyModelSpec(spec),true);spec.population.ageMin=65;assert.equal(verifyModelSpec(spec),false)});
