const test = require('node:test');
const assert = require('node:assert/strict');
const { evaluateResult } = require('../src/quality');

function validResult() { return { status: 'completed', weightRule: 'WTMEC2YR / 6', flow: { merged: 100, adults: 90, complete_phq9: 80, analytic_complete_case: 70, depression_cases: 8 }, coefficients: [{ effect: 0.97, ci_low: 0.9, ci_high: 1.03, p_value: 0.2 }], sensitivityCoefficients: [{ effect: 1, ci_low: .8, ci_high: 1.2, p_value: .9 }], runtime: { rVersion: 'R 4.2', completedAt: '2026-01-01' } }; }
test('valid survey result passes the publication quality gate', () => { const qc = evaluateResult(validResult()); assert.equal(qc.status, 'passed'); assert.equal(qc.summary.failed, 0); });
test('invalid sample flow and confidence interval block publication', () => { const value = validResult(); value.flow.depression_cases = 100; value.coefficients[0].ci_low = 2; const qc = evaluateResult(value); assert.equal(qc.status, 'failed'); assert.ok(qc.summary.failed >= 2); });
test('legacy generic continuous result remains readable but reports new diagnostic warnings',()=>{const result={analysisMode:'generic_survey_v1',status:'completed',weightRule:'WTMEC2YR / 1',flow:{merged:100,population_eligible:90,analytic_complete_case:80},coefficients:[{term:'analysis_exposure',effect:-0.5,ci_low:-0.8,ci_high:-0.2,p_value:0.01,effect_type:'beta'}],sensitivityCoefficients:[],modelSpecDigest:'a'.repeat(64),runtime:{rVersion:'R 4',completedAt:'now'}};const quality=evaluateResult(result);assert.equal(quality.status,'passed');assert.equal(quality.summary.warnings,7);});
test('generic v2 stays compatible while requiring its original diagnostics',()=>{const exposure={term:'analysis_exposure',effect:-.5,ci_low:-.8,ci_high:-.2,p_value:.01,effect_type:'beta'},result={analysisMode:'generic_survey_v2',status:'completed',weightRule:'WTMEC2YR / 1',flow:{merged:100,population_eligible:90,analytic_complete_case:80},coefficients:[exposure],sensitivityCoefficients:[{...exposure,model:'unadjusted'},{...exposure,model:'weight_trim_1_99'}],weightDiagnostics:{min:.1,p01:.2,median:.5,p99:1,max:2,positive:80},designDiagnostics:{degreesFreedom:12,strata:15,psu:30},modelSpecDigest:'a'.repeat(64),runtime:{rVersion:'R 4',completedAt:'now'}};const quality=evaluateResult(result);assert.equal(quality.status,'passed');assert.equal(quality.summary.warnings,4);delete result.weightDiagnostics;assert.equal(evaluateResult(result).status,'failed')});
test('generic v3 requires coherent missingness and model stability diagnostics',()=>{const exposure={term:'analysis_exposure',effect:-.5,ci_low:-.8,ci_high:-.2,p_value:.01,effect_type:'beta'},missingnessDiagnostics=['analysis_outcome','analysis_exposure','analysis_weight','SDMVSTRA','SDMVPSU'].map((variable,index)=>({variable,missing_n:index,missing_pct:index/90*100})),result={analysisMode:'generic_survey_v3',status:'completed',weightRule:'WTMEC2YR / 1',flow:{merged:100,population_eligible:90,analytic_complete_case:80},coefficients:[exposure],sensitivityCoefficients:[{...exposure,model:'unadjusted'},{...exposure,model:'weight_trim_1_99'}],weightDiagnostics:{min:.1,p01:.2,median:.5,p99:1,max:2,positive:80},designDiagnostics:{degreesFreedom:12,strata:15,psu:30},missingnessDiagnostics,completeCaseDiagnostics:{populationN:90,completeN:80,retention:80/90},modelDiagnostics:{converged:true,rank:3,parameters:3,residualDf:12,conditionNumber:5},modelSpecDigest:'a'.repeat(64),runtime:{rVersion:'R 4',completedAt:'now'}};const quality=evaluateResult(result);assert.equal(quality.status,'passed');assert.equal(quality.summary.warnings,0);delete result.modelDiagnostics;assert.equal(evaluateResult(result).status,'failed')});
test('null numeric results can never pass the generic publication gate',()=>{const result={analysisMode:'generic_survey_v3',status:'completed',weightRule:'WTMEC2YR / 1',flow:{merged:100,population_eligible:90,analytic_complete_case:80},coefficients:[{term:'analysis_exposure',effect:null,ci_low:null,ci_high:null,p_value:null,effect_type:'beta'}],modelSpecDigest:'a'.repeat(64),runtime:{rVersion:'R',completedAt:'now'}};assert.equal(evaluateResult(result).status,'failed')});
