const test=require('node:test'),assert=require('node:assert/strict');
const {projects,saveCandidate,saveCandidates}=require('../src/orchestrator');
const {buildVariableCoverage}=require('../src/variable-coverage');
test('changing a candidate invalidates all derived approvals and dynamic mappings',()=>{
 const project={id:'prj_aabbccddeeff0011',status:'awaiting_approval',intent:{cycles:['2017-2018']},variables:[{role:'design',variable:'WTMEC2YR'},{role:'exposure',variable:'OLD',confirmationStatus:'codebook_and_cleaning_approved'}],candidateSelections:[],variableDiscovery:{candidates:[{role:'exposure',items:[{variable:'NEW',file:'LAB_J',matchedCycles:['2017-2018']}]}]},codebookReviews:[{variable:'OLD'}],cleaningApproval:{digest:'old'},modelSpec:{digest:'stale'},events:[],approvals:[],createdAt:new Date().toISOString()};
 projects.set(project.id,project);const result=saveCandidate(project.id,{role:'exposure',variable:'NEW',file:'LAB_J',reason:'better evidence'});assert.equal(result.cleaningApproval,undefined);assert.equal(result.modelSpec,undefined);assert.deepEqual(result.codebookReviews,[]);assert.equal(result.variables.some(x=>x.variable==='OLD'),false);
});
test('bulk Agent recommendations keep multiple covariates from one data file',()=>{const cycles=['2017-2018'],project={id:'prj_1122334455667788',status:'awaiting_approval',intent:{cycles},variables:[{role:'design',variable:'WTMEC2YR',cycles}],candidateSelections:[],variableDiscovery:{candidates:[{role:'covariate',concept:'age',items:[{variable:'RIDAGEYR',file:'DEMO_J',matchedCycles:cycles}]},{role:'covariate',concept:'sex',items:[{variable:'RIAGENDR',file:'DEMO_J',matchedCycles:cycles}]}]},events:[],approvals:[],createdAt:new Date().toISOString()};projects.set(project.id,project);const result=saveCandidates(project.id,{acknowledgeRecommendations:true,items:[{role:'covariate',concept:'age',variable:'RIDAGEYR',file:'DEMO_J',reason:'official match'},{role:'covariate',concept:'sex',variable:'RIAGENDR',file:'DEMO_J',reason:'official match'}]});assert.equal(result.candidateSelections.length,2);assert.throws(()=>saveCandidates(project.id,{items:[]}))});
test('coverage-aware bulk selection rejects stale or unreviewed matrices',()=>{
 const cycles=['2017-2018'],candidates=[{role:'exposure',concept:'lead',items:[{variable:'LBXBPB',file:'PBCD_J',description:'Blood lead',matchedCycles:cycles,score:4}]},{role:'outcome',concept:'sleep',items:[{variable:'SLD012',file:'SLQ_J',description:'Sleep hours',matchedCycles:cycles,score:2}]}],coverage=buildVariableCoverage({cycles},candidates),project={id:'prj_coverage00112233',status:'awaiting_approval',intent:{cycles,exposure:{term:'lead'},outcome:{term:'sleep'}},variables:[],candidateSelections:[],variableDiscovery:{candidates,coverage,coverageDigest:coverage.digest},events:[],approvals:[],createdAt:new Date().toISOString()};
 const items=coverage.recommendations.map(item=>({role:item.role,concept:item.concept,variable:item.variable,file:item.file,reason:'reviewed official recommendation'}));projects.set(project.id,project);
 assert.throws(()=>saveCandidates(project.id,{acknowledgeRecommendations:true,acknowledgeCrossCycleReview:true,coverageDigest:'stale',items}),/已变化/);
 assert.throws(()=>saveCandidates(project.id,{acknowledgeRecommendations:true,coverageDigest:coverage.digest,items}),/跨周期/);
 const result=saveCandidates(project.id,{acknowledgeRecommendations:true,acknowledgeCrossCycleReview:true,coverageDigest:coverage.digest,items});assert.equal(result.candidateSelections.length,2);
});
