const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const steps=['问题解析','变量匹配','文献检索','方案生成','统计分析','报告输出'];
const rows=[['暴露','25(OH)D','LBXVIDMS','VID','统一 nmol/L'],['结局','PHQ-9','DPQ010–090','DPQ','求和后 ≥10'],['协变量','年龄','RIDAGEYR','DEMO','≥20 岁'],['协变量','性别','RIAGENDR','DEMO','分类'],['协变量','种族/族裔','RIDRETH1','DEMO','统一编码'],['协变量','贫困收入比','INDFMPIR','DEMO','连续'],['协变量','BMI','BMXBMI','BMX','连续'],['设计','MEC 权重','WTMEC2YR','DEMO','除以 6'],['设计','分层','SDMVSTRA','DEMO','保留'],['设计','PSU','SDMVPSU','DEMO','保留']];
const papers=[['Vitamin D status and depression in US adults','NHANES 横断面研究；低维生素 D 与抑郁症状相关。','PMID 25743927'],['Serum vitamin D and depressive symptoms','多变量加权回归；校正季节、社会经济和生活方式。','PMID 25112131'],['Vitamin D deficiency and mental health','系统综述；强调异质性、反向因果和残余混杂。','PMID 23377209']];
const code=['library(nhanesA)','library(survey)','library(dplyr)','','# 按周期下载 DEMO / VID / DPQ / BMX，以 SEQN 左连接','analytic <- merged |>','  filter(RIDAGEYR >= 20, pregnancy != 1) |>','  mutate(depression = phq9_total >= 10,','         weight_12yr = WTMEC2YR / 6)','','dsgn <- svydesign(ids = ~SDMVPSU,','  strata = ~SDMVSTRA, weights = ~weight_12yr,','  nest = TRUE, data = analytic)','','model_3 <- svyglm(depression ~ vitamin_d + age + sex +','  race + education + pir + bmi + smoking + activity,','  design = dsgn, family = quasibinomial())'];
const tabs={design:`<div class="title"><h3>研究设计摘要</h3><span class="confidence">方案完整度 92%</span></div><div class="design"><div class="card"><label>研究问题 · PEO</label><p>在美国成年人中，较低血清 25(OH)D 是否与更高的临床显著抑郁症状患病率相关？</p></div><div class="card"><label>研究设计</label><p>合并 6 个周期的横断面研究；校正 NHANES 复杂抽样设计。</p></div><div class="card"><label>暴露</label><p><b>血清 25(OH)D</b>：连续值、四分位数和临床分层。</p></div><div class="card"><label>结局</label><p><b>PHQ-9 ≥ 10</b>；连续评分作为敏感性分析。</p></div><div class="card wide"><label>协变量</label><div class="tags">${['年龄','性别','种族/族裔','教育','PIR','BMI','吸烟','体力活动','慢性病','季节'].map(x=>`<span>${x}</span>`).join('')}</div></div><div class="card wide"><label>统计计划</label><ol><li>合并周期后重算 12 年 MEC 权重，绘制样本纳入流程。</li><li>Survey-weighted logistic regression，递进构建三个模型。</li><li>限制性立方样条检验非线性，预设亚组和交互分析。</li><li>多重插补、结局阈值与极端值敏感性分析。</li></ol></div></div>`,variables:`<div class="title"><h3>NHANES 变量映射</h3><span class="confidence">周期覆盖已校验</span></div><table class="table"><thead><tr><th>角色</th><th>概念</th><th>变量</th><th>文件</th><th>处理</th></tr></thead><tbody>${rows.map(r=>`<tr><td><span class="badge">${r[0]}</span></td><td>${r[1]}</td><td><code>${r[2]}</code></td><td>${r[3]}</td><td>${r[4]}</td></tr>`).join('')}</tbody></table>`,literature:`<div class="title"><h3>文献证据</h3><span class="confidence">PubMed · 12 篇</span></div>${papers.map(p=>`<article class="paper"><h4>${p[0]}</h4><p>${p[1]}</p><span class="confidence">${p[2]}</span></article>`).join('')}<article class="paper"><h4>方法学综合</h4><p>本方案明确跨周期谐调，并预设非线性、亚组和多重插补。</p></article>`,code:`<div class="title"><h3>可复现 R 分析骨架</h3><span class="confidence">R · survey / nhanesA</span></div><pre class="code">${code.join('\n')}</pre>`,qc:`<div class="title"><h3>执行前质量门</h3><span class="confidence">7 / 8 通过</span></div>${['SEQN 合并键唯一','周期变量映射完整','周期权重分母正确','PSU 与 strata 已纳入','结局缺失码已处理','暴露单位完成谐调','极端权重与孤立 PSU 已检查'].map(x=>`<div class="check"><b>✓　</b>${x}</div>`).join('')}<div class="check"><span style="color:#b7792c">!　</span><b>待确认：</b>早期周期维生素 D 测定值转换规则。</div>`};
function pipeline(n=3){$('#pipeline').innerHTML=steps.map((x,i)=>`<div class="step ${i<=n?'active':''}"><span>${i<n?'✓':i+1}</span>${x}</div>`).join('')}
function tab(name){$$('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));$('#tabContent').innerHTML=tabs[name]}
function logs(){const a=[['研究问题已结构化','识别暴露、结局、人群与周期'],['匹配 10 个核心变量','覆盖 6 个调查周期'],['检索 PubMed 文献','筛选 12 篇相关研究'],['研究方案已生成','纳入复杂抽样设计与敏感性分析']];$('#logs').innerHTML=a.map((x,i)=>`<div class="log"><span>${i<3?'✓':'✦'}</span><div><b>${x[0]}</b><p>${x[1]}</p><small>00:${String(2+i*3).padStart(2,'0')}</small></div></div>`).join('')}
function toast(x){$('#toast').textContent=x;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2000)}
$$('[data-example]').forEach(b=>b.onclick=()=>$('#question').value=b.dataset.example);$$('[data-add]').forEach(b=>b.onclick=()=>$('#question').value+=($('#question').value?'；':'')+b.dataset.add);$$('[data-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.tab));
$('#run').onclick=()=>{if(!$('#question').value)$('#question').value=$$('[data-example]')[0].dataset.example;$('#start').classList.add('hidden');$('#results').classList.remove('hidden');window.scrollTo(0,0)};$('#newStudy').onclick=()=>{$('#results').classList.add('hidden');$('#start').classList.remove('hidden');$('#question').value=''};$('#continue').onclick=()=>{pipeline(5);tab('qc');toast('演示分析已完成')};$('#export').onclick=()=>{const b=new Blob(['# NHANES 研究方案\n\n- 周期：2007–2018\n- 设计：复杂抽样加权横断面研究\n'],{type:'text/markdown'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='nhanes-study-protocol.md';a.click();toast('方案已导出')};pipeline();logs();tab('design');
