const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const steps=['问题解析','变量匹配','文献检索','方案生成','统计分析','报告输出'];
const rows=[['暴露','25(OH)D','LBXVIDMS','VID','统一 nmol/L'],['结局','PHQ-9','DPQ010–090','DPQ','求和后 ≥10'],['协变量','年龄','RIDAGEYR','DEMO','≥20 岁'],['协变量','性别','RIAGENDR','DEMO','分类'],['协变量','种族/族裔','RIDRETH1','DEMO','统一编码'],['协变量','贫困收入比','INDFMPIR','DEMO','连续'],['协变量','BMI','BMXBMI','BMX','连续'],['设计','MEC 权重','WTMEC2YR','DEMO','除以 6'],['设计','分层','SDMVSTRA','DEMO','保留'],['设计','PSU','SDMVPSU','DEMO','保留']];
const papers=[['Vitamin D status and depression in US adults','NHANES 横断面研究；低维生素 D 与抑郁症状相关。','PMID 25743927'],['Serum vitamin D and depressive symptoms','多变量加权回归；校正季节、社会经济和生活方式。','PMID 25112131'],['Vitamin D deficiency and mental health','系统综述；强调异质性、反向因果和残余混杂。','PMID 23377209']];
const code=['library(nhanesA)','library(survey)','library(dplyr)','','# 按周期下载 DEMO / VID / DPQ / BMX，以 SEQN 左连接','analytic <- merged |>','  filter(RIDAGEYR >= 20, pregnancy != 1) |>','  mutate(depression = phq9_total >= 10,','         weight_12yr = WTMEC2YR / 6)','','dsgn <- svydesign(ids = ~SDMVPSU,','  strata = ~SDMVSTRA, weights = ~weight_12yr,','  nest = TRUE, data = analytic)','','model_3 <- svyglm(depression ~ vitamin_d + age + sex +','  race + education + pir + bmi + smoking + activity,','  design = dsgn, family = quasibinomial())'];
const tabs={design:`<div class="title"><h3>研究设计摘要</h3><span class="confidence">方案完整度 92%</span></div><div class="design"><div class="card"><label>研究问题 · PEO</label><p>在美国成年人中，较低血清 25(OH)D 是否与更高的临床显著抑郁症状患病率相关？</p></div><div class="card"><label>研究设计</label><p>合并 6 个周期的横断面研究；校正 NHANES 复杂抽样设计。</p></div><div class="card"><label>暴露</label><p><b>血清 25(OH)D</b>：连续值、四分位数和临床分层。</p></div><div class="card"><label>结局</label><p><b>PHQ-9 ≥ 10</b>；连续评分作为敏感性分析。</p></div><div class="card wide"><label>协变量</label><div class="tags">${['年龄','性别','种族/族裔','教育','PIR','BMI','吸烟','体力活动','慢性病','季节'].map(x=>`<span>${x}</span>`).join('')}</div></div><div class="card wide"><label>统计计划</label><ol><li>合并周期后重算 12 年 MEC 权重，绘制样本纳入流程。</li><li>Survey-weighted logistic regression，递进构建三个模型。</li><li>限制性立方样条检验非线性，预设亚组和交互分析。</li><li>多重插补、结局阈值与极端值敏感性分析。</li></ol></div></div>`,variables:`<div class="title"><h3>NHANES 变量映射</h3><span class="confidence">周期覆盖已校验</span></div><table class="table"><thead><tr><th>角色</th><th>概念</th><th>变量</th><th>文件</th><th>处理</th></tr></thead><tbody>${rows.map(r=>`<tr><td><span class="badge">${r[0]}</span></td><td>${r[1]}</td><td><code>${r[2]}</code></td><td>${r[3]}</td><td>${r[4]}</td></tr>`).join('')}</tbody></table>`,literature:`<div class="title"><h3>文献证据</h3><span class="confidence">PubMed · 12 篇</span></div>${papers.map(p=>`<article class="paper"><h4>${p[0]}</h4><p>${p[1]}</p><span class="confidence">${p[2]}</span></article>`).join('')}<article class="paper"><h4>方法学综合</h4><p>本方案明确跨周期谐调，并预设非线性、亚组和多重插补。</p></article>`,code:`<div class="title"><h3>可复现 R 分析骨架</h3><span class="confidence">R · survey / nhanesA</span></div><pre class="code">${code.join('\n')}</pre>`,qc:`<div class="title"><h3>执行前质量门</h3><span class="confidence">7 / 8 通过</span></div>${['SEQN 合并键唯一','周期变量映射完整','周期权重分母正确','PSU 与 strata 已纳入','结局缺失码已处理','暴露单位完成谐调','极端权重与孤立 PSU 已检查'].map(x=>`<div class="check"><b>✓　</b>${x}</div>`).join('')}<div class="check"><span style="color:#b7792c">!　</span><b>待确认：</b>早期周期维生素 D 测定值转换规则。</div>`};
function pipeline(n=3){$('#pipeline').innerHTML=steps.map((x,i)=>`<div class="step ${i<=n?'active':''}"><span>${i<n?'✓':i+1}</span>${x}</div>`).join('')}
function tab(name){$$('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));$('#tabContent').innerHTML=tabs[name];if(name==='variables')bindCatalogSearch()}
function logs(){const a=[['研究问题已结构化','识别暴露、结局、人群与周期'],['匹配 10 个核心变量','覆盖 6 个调查周期'],['检索 PubMed 文献','筛选 12 篇相关研究'],['研究方案已生成','纳入复杂抽样设计与敏感性分析']];$('#logs').innerHTML=a.map((x,i)=>`<div class="log"><span>${i<3?'✓':'✦'}</span><div><b>${x[0]}</b><p>${x[1]}</p><small>00:${String(2+i*3).padStart(2,'0')}</small></div></div>`).join('')}
function toast(x){$('#toast').textContent=x;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2000)}
$$('[data-example]').forEach(b=>b.onclick=()=>$('#question').value=b.dataset.example);$$('[data-add]').forEach(b=>b.onclick=()=>$('#question').value+=($('#question').value?'；':'')+b.dataset.add);$$('[data-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.tab));
let activeProject=null,eventSource=null;
function syncProject(project){activeProject=project;const intent=project.intent||{},population=intent.population||{},cycles=intent.cycles||[];$('#studyTitle').textContent=project.title||'未命名研究';$('#studyCycle').textContent=`ACTIVE STUDY · NHANES ${cycles.length?`${cycles[0]} 至 ${cycles.at(-1)}`:'周期待确认'}`;$('#studyPopulation').textContent=`美国 ${population.ageMin?`${population.ageMin} 岁以上`:'年龄待确认'}人群 · 复杂抽样横断面研究`;const ambiguity=(intent.ambiguities||[]).map(x=>`• ${esc(x)}`).join('<br>')||'自动识别已完成，仍需研究者确认。';$('#researcherWarning').innerHTML=`<b>!　研究者确认点</b><br>${ambiguity}`;tabs.design=designTab(project);tabs.variables=variablesTab(project);tab('design')}
function designTab(project){const i=project.intent||{},p=i.population||{},cov=i.covariates||[];return `<div class="title"><h3>研究问题结构化结果</h3><span class="confidence">${esc(i.parser?.mode||'解析中')}</span></div><div class="design"><div class="card"><label>暴露</label><p><b>${esc(i.exposure?.label||'待识别')}</b><br>置信度 ${Math.round((i.exposure?.confidence||0)*100)}%</p></div><div class="card"><label>结局</label><p><b>${esc(i.outcome?.label||'待识别')}</b><br>置信度 ${Math.round((i.outcome?.confidence||0)*100)}%</p></div><div class="card"><label>目标人群</label><p>美国 ${p.ageMin?`${esc(p.ageMin)} 岁以上`:'年龄待确认'}；妊娠状态：${esc(p.pregnancy||'待确认')}</p></div><div class="card"><label>NHANES 周期</label><p>${(i.cycles||[]).map(esc).join('、')||'待确认'}</p></div><div class="card wide"><label>候选协变量</label><div class="tags">${cov.map(x=>`<span>${esc(x)}</span>`).join('')}</div></div><div class="card wide"><label>原始研究问题</label><p>${esc(project.question)}</p></div></div>`}
function variablesTab(project){const i=project.intent||{},component=i.exposure?.component||'Laboratory',cycle=i.cycles?.at(-1)||'2017-2018';const mapped=(project.variables||rows.map(r=>({role:r[0],concept:r[1],variable:r[2],source:r[3],transform:r[4]})));return `<div class="title"><h3>NHANES 变量映射</h3><span class="confidence">CDC/NCHS 官方目录</span></div><div class="catalog-search"><select id="cdcComponent">${['Laboratory','Questionnaire','Dietary','Examination','Demographics'].map(x=>`<option ${x===component?'selected':''}>${x}</option>`).join('')}</select><input id="cdcCycle" value="${esc(cycle)}" aria-label="NHANES 周期"><input id="cdcQuery" value="${esc(i.exposure?.label||'')}" placeholder="变量名或概念"><button id="cdcSearch" class="primary">搜索官方变量</button></div><div id="cdcResults" class="catalog-results"><small>点击“搜索官方变量”查询 CDC 实时目录；结果必须由研究者确认。</small></div><table class="table"><thead><tr><th>角色</th><th>概念</th><th>变量</th><th>文件</th><th>处理</th></tr></thead><tbody>${mapped.map(r=>`<tr><td><span class="badge">${esc(r.role)}</span></td><td>${esc(r.concept)}</td><td><code>${esc(r.variable)}</code></td><td>${esc(r.source)}</td><td>${esc(r.transform)}</td></tr>`).join('')}</tbody></table>`}
function bindCatalogSearch(){const button=$('#cdcSearch');if(!button)return;button.onclick=async()=>{button.disabled=true;button.textContent='查询中…';try{const params=new URLSearchParams({component:$('#cdcComponent').value,cycle:$('#cdcCycle').value,q:$('#cdcQuery').value,limit:'20'}),response=await fetch(`/api/catalog/cdc?${params}`),data=await response.json();if(!response.ok)throw new Error(data.error?.message||'CDC 查询失败');$('#cdcResults').innerHTML=data.items.length?`<table class="table"><thead><tr><th>变量</th><th>说明</th><th>文件</th><th>周期</th></tr></thead><tbody>${data.items.map(x=>`<tr><td><code>${esc(x.variable)}</code></td><td>${esc(x.description)}</td><td>${esc(x.file)}</td><td>${esc(x.beginYear)}–${esc(x.endYear)}</td></tr>`).join('')}</tbody></table><small>来源：${esc(data.source)} · ${esc(data.totalMatched)} 个匹配结果</small>`:'<p>没有找到匹配变量，请更换英文关键词或周期。</p>'}catch(error){$('#cdcResults').innerHTML=`<p>${esc(error.message)}</p>`}finally{button.disabled=false;button.textContent='搜索官方变量'}}}
$('#run').onclick=async()=>{if(!$('#question').value)$('#question').value=$$('[data-example]')[0].dataset.example;try{const response=await fetch('/api/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:$('#question').value})});const payload=await response.json();if(!response.ok)throw new Error(payload.error?.message||'创建项目失败');syncProject(payload);$('#start').classList.add('hidden');$('#results').classList.remove('hidden');window.scrollTo(0,0);eventSource=new EventSource(`/api/projects/${activeProject.id}/events`);eventSource.onmessage=async e=>{const event=JSON.parse(e.data),index=['parse','variables','literature','protocol','analysis','quality','report'].indexOf(event.stage);if(index>=0)pipeline(Math.min(index,5));if(event.status==='blocked'){const latest=await fetch(`/api/projects/${activeProject.id}`).then(r=>r.json());syncProject(latest);toast('方案已生成，等待研究者确认');eventSource.close()}};await fetch(`/api/projects/${activeProject.id}/run`,{method:'POST'})}catch(error){toast(error.message)}};
$('#newStudy').onclick=()=>{eventSource?.close();activeProject=null;$('#results').classList.add('hidden');$('#start').classList.remove('hidden');$('#question').value=''};
$('#continue').onclick=async()=>{if(activeProject){const response=await fetch(`/api/projects/${activeProject.id}/approve`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({actor:'researcher',decisions:{outcome_definition:'PHQ-9 >= 10',covariate_set:'extended'}})});if(!response.ok){toast('请等待方案生成完成');return}}pipeline(5);tab('qc');toast('方案已确认；分析执行器为下一阶段')};
$('#export').onclick=()=>{const b=new Blob(['# NHANES 研究方案\n\n- 周期：2007–2018\n- 设计：复杂抽样加权横断面研究\n'],{type:'text/markdown'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='nhanes-study-protocol.md';a.click();toast('方案已导出')};pipeline();logs();tab('design');
