const crypto = require('crypto');

function assessReadiness(project) {
  const variables = project.variables || [], roles = new Set(variables.map(item => item.role));
  const errors = [], warnings = [];
  for (const role of ['exposure', 'outcome', 'design']) if (!roles.has(role)) errors.push(`missing confirmed ${role} variable`);
  if (!project.protocol) errors.push('analysis protocol is not ready');
  if (!project.intent?.cycles?.length) errors.push('NHANES cycles are not defined');
  if (!variables.some(item => item.variable === 'WTMEC2YR')) errors.push('MEC examination weight is not confirmed');
  if (!variables.some(item => item.variable === 'SDMVSTRA') || !variables.some(item => item.variable === 'SDMVPSU')) errors.push('survey strata or PSU is not confirmed');
  if (!project.evidence?.summary?.included) warnings.push('no screened PubMed evidence has been included');
  for (const ambiguity of project.intent?.ambiguities || []) warnings.push(ambiguity);
  return { ready: errors.length === 0, errors, warnings };
}

function generateRProject(project) {
  const readiness = assessReadiness(project), cycles = project.intent?.cycles || [], variables = project.variables || [];
  const config = {
    schemaVersion: '1.0', projectId: project.id, generatedAt: new Date().toISOString(), question: project.question,
    cycles, weightDivisor: cycles.length || null, variables: variables.map(({ role, concept, variable, source, transform, cycles: coverage }) => ({ role, concept, variable, source, transform, cycles: coverage })),
    includedPmids: (project.evidence?.items || []).filter(item => item.decision === 'include').map(item => item.pmid),
    protocol: project.protocol, readiness, status: readiness.ready ? 'generated_not_executed' : 'blocked_not_executable'
  };
  const ageMin = project.intent?.population?.ageMin || 18;
  const r = [
    '# Generated by NHANES Research Agent. Review before execution.',
    'library(nhanesA)', 'library(survey)', 'library(dplyr)', 'library(purrr)', '',
    'options(survey.lonely.psu = "adjust")', 'set.seed(20260901)', `cycles <- c(${cycles.map(x => `"${x}"`).join(', ')})`, '',
    '# TODO: download the frozen component files listed in analysis-spec.json.',
    '# TODO: harmonize cycle-specific variable names, units, missing codes and assay changes.',
    '# Every join must first assert uniqueness of SEQN and preserve a sample-flow count.',
    'stopifnot(exists("merged"))', 'stopifnot(!anyDuplicated(merged$SEQN))', '',
    'analytic <- merged |>', `  filter(RIDAGEYR >= ${ageMin}) |>`, `  mutate(pooled_weight = WTMEC2YR / ${cycles.length || 1})`, '',
    'stopifnot(all(c("SDMVPSU", "SDMVSTRA", "pooled_weight") %in% names(analytic)))',
    'design <- svydesign(ids = ~SDMVPSU, strata = ~SDMVSTRA,', '  weights = ~pooled_weight, nest = TRUE, data = analytic)', '',
    '# Model formula must be finalized from confirmed exposure/outcome transformations.',
    '# Example only; the script stops until derived variables are explicitly created.',
    'stopifnot(all(c("analysis_outcome", "analysis_exposure") %in% names(analytic)))',
    'model <- svyglm(analysis_outcome ~ analysis_exposure + RIDAGEYR + RIAGENDR +',
    '  RIDRETH1 + INDFMPIR + BMXBMI, design = design, family = quasibinomial())', '',
    'ci <- confint(model)', 'stopifnot(all(is.finite(coef(model))), all(is.finite(ci)))',
    'dir.create("artifacts", showWarnings = FALSE)',
    'saveRDS(list(model = model, confint = ci, session = sessionInfo()), "artifacts/results.rds")'
  ].join('\n');
  const qcRows = [
    ['check', 'severity', 'rule'], ['readiness', 'error', readiness.ready ? 'passed before generation' : readiness.errors.join('; ')],
    ['merge_uniqueness', 'error', 'SEQN is unique before every join'], ['join_growth', 'error', 'row count cannot grow unexpectedly after joins'],
    ['sample_flow', 'error', 'every exclusion has before and after counts'], ['weight', 'error', `pooled weight divisor equals ${cycles.length || 'included'} cycles`],
    ['survey_design', 'error', 'PSU strata and analysis weight are present'], ['degrees_freedom', 'error', 'survey design degrees of freedom are positive'],
    ['missing_codes', 'error', 'special missing codes are converted to NA'], ['model', 'error', 'coefficients and confidence limits are finite'],
    ['report', 'error', 'every reported number has an artifact path']
  ];
  const files = {
    'analysis-spec.json': JSON.stringify(config, null, 2), 'analysis.R': r,
    'qc-rules.csv': qcRows.map(row => row.map(value => `"${String(value).replaceAll('"', '""')}"`).join(',')).join('\n'),
    'README.md': `# NHANES analysis package\n\nStatus: **${config.status}** — generated, not executed.\n\n## Blocking errors\n${readiness.errors.map(x => `- ${x}`).join('\n') || '- None'}\n\n## Warnings\n${readiness.warnings.map(x => `- ${x}`).join('\n') || '- None'}\n\nVerify CDC codebooks, transformations, eligibility, survey weights and all derived variables before running.\n`
  };
  const manifest = Object.entries(files).map(([name, content]) => ({ name, bytes: Buffer.byteLength(content), sha256: crypto.createHash('sha256').update(content).digest('hex') }));
  files['manifest.json'] = JSON.stringify({ generatedAt: config.generatedAt, files: manifest }, null, 2);
  return { status: config.status, readiness, files };
}

module.exports = { assessReadiness, generateRProject };
