const crypto = require('crypto');
const { buildDataManifest } = require('./data-manifest');

function assessReadiness(project) {
  const variables = project.variables || [], roles = new Set(variables.map(item => item.role));
  const errors = [], warnings = [];
  for (const role of ['exposure', 'outcome', 'design']) if (!roles.has(role)) errors.push(`missing confirmed ${role} variable`);
  if (!project.protocol) errors.push('analysis protocol is not ready');
  if (!project.intent?.cycles?.length) errors.push('NHANES cycles are not defined');
  const requiredWeight=project.modelSpec?.weightVariable||'WTMEC2YR';
  if (!variables.some(item => item.variable === requiredWeight)) errors.push(`${requiredWeight} analysis weight is not confirmed`);
  if (!variables.some(item => item.variable === 'SDMVSTRA') || !variables.some(item => item.variable === 'SDMVPSU')) errors.push('survey strata or PSU is not confirmed');
  const usesReviewedMappings = variables.some(item => item.confirmationStatus === 'codebook_and_cleaning_approved');
  if (usesReviewedMappings && !project.modelSpec) errors.push('statistical model specification is not approved');
  if (project.modelSpec && !require('./model-spec').verifyModelSpec(project.modelSpec)) errors.push('model specification digest is invalid');
  if (project.modelSpec && project.modelSpec.cleaningDigest !== project.cleaningApproval?.digest) errors.push('model specification does not match the current cleaning approval');
  if (!project.evidence?.summary?.included) warnings.push('no screened PubMed evidence has been included');
  for (const ambiguity of project.intent?.ambiguities || []) warnings.push(ambiguity);
  return { ready: errors.length === 0, errors, warnings };
}

function generateRProject(project) {
  const readiness = assessReadiness(project), cycles = project.intent?.cycles || [], variables = project.variables || [];
  const dataManifest = buildDataManifest(project);
  const config = {
    schemaVersion: '1.0', projectId: project.id, generatedAt: new Date().toISOString(), question: project.question,
    cycles, weightDivisor: project.modelSpec?.weightPolicy?.divisor||cycles.length||null, variables: variables.map(({ role, concept, variable, source, transform, cycles: coverage }) => ({ role, concept, variable, source, transform, cycles: coverage })),
    includedPmids: (project.evidence?.items || []).filter(item => item.decision === 'include').map(item => item.pmid),
    protocol: project.protocol, modelSpec: project.modelSpec || null, codebookEvidence: project.codebookReviews || [], candidateSelections: project.candidateSelections || [], dataManifest, readiness, status: readiness.ready ? 'generated_not_executed' : 'blocked_not_executable'
  };
  const ageMin = project.intent?.population?.ageMin || 18,modelWeight=project.modelSpec?.weightVariable||'WTMEC2YR',weightDivisor=project.modelSpec?.weightPolicy?.divisor||cycles.length||1;
  if(!/^[A-Z][A-Z0-9_]{0,39}$/.test(modelWeight)||!Number.isInteger(Number(weightDivisor))||Number(weightDivisor)<1)throw new Error('invalid frozen weight policy');
  const r = [
    '# Generated by NHANES Research Agent. Review before execution.',
    'library(nhanesA)', 'library(survey)', 'library(dplyr)', 'library(purrr)', '',
    'options(survey.lonely.psu = "adjust")', 'set.seed(20260901)', `cycles <- c(${cycles.map(x => `"${x}"`).join(', ')})`, '',
    '# TODO: download the frozen component files listed in analysis-spec.json.',
    '# TODO: harmonize cycle-specific variable names, units, missing codes and assay changes.',
    '# Every join must first assert uniqueness of SEQN and preserve a sample-flow count.',
    'stopifnot(exists("merged"))', 'stopifnot(!anyDuplicated(merged$SEQN))', '',
    'analytic <- merged |>', `  mutate(pooled_weight = ${modelWeight} / ${weightDivisor},`, `         .target_population = is.finite(RIDAGEYR) & RIDAGEYR >= ${ageMin})`, '',
    'stopifnot(all(c("SDMVPSU", "SDMVSTRA", "pooled_weight") %in% names(analytic)))',
    'design_source <- analytic |>', '  filter(complete.cases(SDMVPSU, SDMVSTRA, pooled_weight),', '         is.finite(pooled_weight), pooled_weight > 0)',
    'full_design <- svydesign(ids = ~SDMVPSU, strata = ~SDMVSTRA,', '  weights = ~pooled_weight, nest = TRUE, data = design_source)', '',
    '# Model formula must be finalized from confirmed exposure/outcome transformations.',
    '# Example only; the script stops until derived variables are explicitly created.',
    'stopifnot(all(c("analysis_outcome", "analysis_exposure") %in% names(analytic)))',
    'full_design <- update(full_design, analysis_outcome = analysis_outcome,', '  analysis_exposure = analysis_exposure)',
    'design <- subset(full_design, .target_population &', '  is.finite(analysis_outcome) & is.finite(analysis_exposure))',
    'model <- svyglm(analysis_outcome ~ analysis_exposure + RIDAGEYR + RIAGENDR +',
    '  RIDRETH1 + INDFMPIR + BMXBMI, design = design, family = quasibinomial())', '',
    'ci <- confint(model)', 'stopifnot(all(is.finite(coef(model))), all(is.finite(ci)))',
    'dir.create("artifacts", showWarnings = FALSE)',
    'saveRDS(list(model = model, confint = ci, session = sessionInfo()), "artifacts/results.rds")'
  ].join('\n');
  const qcRows = [
    ['check', 'severity', 'rule'], ['readiness', 'error', readiness.ready ? 'passed before generation' : readiness.errors.join('; ')],
    ['merge_uniqueness', 'error', 'SEQN is unique before every join'], ['join_growth', 'error', 'row count cannot grow unexpectedly after joins'],
    ['sample_flow', 'error', 'every exclusion has before and after counts'], ['weight', 'error', `pooled weight rule equals ${modelWeight} / ${weightDivisor}`],
    ['survey_design', 'error', 'PSU strata and analysis weight are present'], ['survey_domain', 'error', 'define the full survey design before subset() enters the analysis domain'], ['degrees_freedom', 'error', 'survey design degrees of freedom are positive'],
    ['missing_codes', 'error', 'special missing codes are converted to NA'], ['model', 'error', 'coefficients and confidence limits are finite'],
    ['report', 'error', 'every reported number has an artifact path']
  ];
  const files = {
    'analysis-spec.json': JSON.stringify(config, null, 2), 'data-manifest.json': JSON.stringify(dataManifest, null, 2), 'analysis.R': r,
    'qc-rules.csv': qcRows.map(row => row.map(value => `"${String(value).replaceAll('"', '""')}"`).join(',')).join('\n'),
    'README.md': `# NHANES analysis package\n\nStatus: **${config.status}** — generated, not executed.\n\n## Blocking errors\n${readiness.errors.map(x => `- ${x}`).join('\n') || '- None'}\n\n## Warnings\n${readiness.warnings.map(x => `- ${x}`).join('\n') || '- None'}\n\nVerify CDC codebooks, transformations, eligibility, survey weights and all derived variables before running.\n`
  };
  const cleaning = require('./cleaning-draft').buildCleaningDraft(project);
  files['cleaning-draft.R'] = cleaning.code;
  files['cleaning-rules.json'] = JSON.stringify({ ...cleaning, code: undefined }, null, 2);
  files['prepare-data.R'] = require('./data-preparation').generatePreparationScript(dataManifest, cleaning);
  files['model.R'] = require('./model-script').generateModelScript(project.modelSpec);
  const manifest = Object.entries(files).map(([name, content]) => ({ name, bytes: Buffer.byteLength(content), sha256: crypto.createHash('sha256').update(content).digest('hex') }));
  files['manifest.json'] = JSON.stringify({ generatedAt: config.generatedAt, files: manifest }, null, 2);
  return { status: config.status, readiness, files };
}

module.exports = { assessReadiness, generateRProject };
