const fs = require('fs'), path = require('path'), crypto = require('crypto');
const { spawn } = require('child_process');
const { createAnalysisArchive } = require('./archive');
const jobs = new Map(), queue = [];
let workerActive = false;
function dataRoot() { return path.resolve(process.env.DATA_ROOT || (process.env.DATABASE_PATH && process.env.DATABASE_PATH !== ':memory:' ? path.dirname(process.env.DATABASE_PATH) : require('os').tmpdir())); }
function safeId(value) { if (!/^prj_[a-f0-9]{16}$/.test(value)) { const error = new Error('invalid project id'); error.status = 400; throw error; } return value; }
function executionGate(project) { const names = new Set((project.variables || []).map(item => item.variable)), errors = []; if (project.status !== 'approved') errors.push('research protocol is not approved'); if (!names.has('LBXVIDMS')) errors.push('supported exposure LBXVIDMS is missing'); if (![...names].some(name => String(name).startsWith('DPQ010'))) errors.push('supported PHQ-9 outcome mapping is missing'); if (!(project.intent?.cycles || []).length) errors.push('no approved NHANES cycles'); return { ready: errors.length === 0, errors }; }
function view(job) { let result = null; if (job.status === 'completed') { try { result = JSON.parse(fs.readFileSync(path.join(job.outputDir, 'result.json'), 'utf8')); } catch {} } return { id: job.id, projectId: job.projectId, status: job.status, gate: job.gate, startedAt: job.startedAt, completedAt: job.completedAt, error: job.error, result }; }
function run(job) { return new Promise(resolve => { job.status = 'running'; fs.mkdirSync(job.outputDir, { recursive: true }); const child = spawn('Rscript', ['/app/runner/analysis.R', job.cacheDir, job.outputDir, String(job.cycles), String(job.ageMin)], { stdio: ['ignore', 'pipe', 'pipe'], env: { PATH: process.env.PATH, HOME: '/tmp', LANG: 'C.UTF-8' } }); let logs = ''; const collect = chunk => { logs = (logs + chunk.toString('utf8')).slice(-16000); }; child.stdout.on('data', collect); child.stderr.on('data', collect); const timer = setTimeout(() => child.kill('SIGKILL'), 10 * 60 * 1000); child.on('error', error => { clearTimeout(timer); job.status = 'failed'; job.error = error.message; job.completedAt = new Date().toISOString(); resolve(); }); child.on('exit', code => { clearTimeout(timer); if (job.completedAt) return; job.status = code === 0 && fs.existsSync(path.join(job.outputDir, 'result.json')) ? 'completed' : 'failed'; job.error = job.status === 'failed' ? (logs.trim() || `R exited with code ${code}`) : null; job.completedAt = new Date().toISOString(); fs.writeFileSync(path.join(job.outputDir, 'execution.log'), logs, { mode: 0o600 }); resolve(); }); }); }
async function drain() { if (workerActive) return; const job = queue.shift(); if (!job) return; workerActive = true; try { await run(job); } finally { workerActive = false; setImmediate(drain); } }
function startAnalysis(project) { safeId(project.id); const gate = executionGate(project); if (!gate.ready) { const error = new Error(gate.errors.join('; ')); error.status = 409; error.code = 'ANALYSIS_NOT_READY'; throw error; } const existing = jobs.get(project.id); if (existing && ['queued', 'running'].includes(existing.status)) return view(existing); const root = dataRoot(), job = { id: `run_${crypto.randomBytes(8).toString('hex')}`, projectId: project.id, status: 'queued', gate, cacheDir: path.join(root, 'xpt-cache', project.id), outputDir: path.join(root, 'results', project.id), cycles: project.intent.cycles.length, ageMin: project.intent.population?.ageMin || 18, startedAt: new Date().toISOString(), completedAt: null, error: null }; if (!fs.existsSync(job.cacheDir)) { const error = new Error('approved XPT data cache is missing'); error.status = 409; error.code = 'DATA_CACHE_MISSING'; throw error; } jobs.set(project.id, job); queue.push(job); setImmediate(drain); return view(job); }
function getAnalysis(projectId) { safeId(projectId); const job = jobs.get(projectId); if (job) return view(job); const outputDir = path.join(dataRoot(), 'results', projectId), resultFile = path.join(outputDir, 'result.json'); if (fs.existsSync(resultFile)) return { projectId, status: 'completed', result: JSON.parse(fs.readFileSync(resultFile, 'utf8')) }; return { projectId, status: 'not_started', result: null }; }
function getAnalysisArchive(projectId) { safeId(projectId); const outputDir = path.join(dataRoot(), 'results', projectId), names = ['result.json', 'model-coefficients.csv', 'sensitivity-coefficients.csv', 'REPORT.md', 'execution.log'], files = {}; for (const name of names) { const file = path.join(outputDir, name); if (fs.existsSync(file)) files[name] = fs.readFileSync(file, 'utf8'); } if (!files['result.json']) { const error = new Error('completed analysis result is missing'); error.status = 404; throw error; } files['result-manifest.json'] = JSON.stringify({ schemaVersion: '1.0', projectId, files: Object.entries(files).map(([name, value]) => ({ name, bytes: Buffer.byteLength(value), sha256: crypto.createHash('sha256').update(value).digest('hex') })) }, null, 2); return createAnalysisArchive({ files }); }
module.exports = { executionGate, startAnalysis, getAnalysis, getAnalysisArchive };
